[toolchain]
channel = "nightly-2024-03-28"
# components = [
#   # Minimal
#   "rustc", "rust-std", "cargo",
#   # Default
#   "rust-docs", "rustfmt", "clippy",
#   # And a little more
#   "rust-src", "llvm-tools", "rust-analyzer"
# ]
profile = "default"
components = [ "rust-src", "rust-analyzer" ]
